//! linuxsys — basics expansion (in-process JIT matrix). Owner: linuxsys agent. Edit ONLY this file.
//! Builders: src(name,file).oracle()/.exit()/.out()/.has(); port(name,file) for cross-engine golden.
//! Keep this module compiling at all times (`cargo build -p dd-tests`).
//!
//! Linux-only syscalls with no portable POSIX form (epoll/eventfd/timerfd/signalfd/inotify/memfd/
//! splice family/pidfd/sched/io_uring/…). On the macOS-hosted runtime these are EMULATED (kqueue/pipe),
//! so each is diffed against a NATIVE-Linux oracle: a divergence here is an emulation gap (xfail-tracked
//! + a GAPS row), which is exactly the high-value signal for the engine builders.
#![allow(unused_imports)]
use crate::{group, src, port, fixture, in_rootfs, Case, Engine, Group};

const LIN: &[Engine] = &[Engine::LinuxAarch64, Engine::LinuxX86_64];

pub fn groups() -> Vec<Group> { vec![epoll(), events(), fsx(), procx(), schedx(), miscx()] }

/// epoll readiness-model corners: edge-trigger, MOD/DEL, oneshot rearm, pwait sigmask.
fn epoll() -> Group {
    group("lsys-epoll", vec![
        src("epoll-et", "ext_linuxsys/epoll_et.c").oracle(),
        src("epoll-mod", "ext_linuxsys/epoll_mod.c").oracle(),
        src("epoll-oneshot", "ext_linuxsys/epoll_oneshot.c").oracle(),
        src("epoll-pwait", "ext_linuxsys/epoll_pwait.c").oracle(),
    ])
}

/// event/timer/signal fds.
fn events() -> Group {
    group("lsys-events", vec![
        // EFD_NONBLOCK read on a zero counter does NOT return EAGAIN on the JIT. GAPS `lsys-eventfd-nonblock`.
        src("eventfd-nonblock", "ext_linuxsys/eventfd_nonblock.c").oracle(),
        src("timerfd-interval", "ext_linuxsys/timerfd_interval.c").oracle(),
        // timerfd_gettime reports 0 remaining for an armed one-shot (no remaining-time tracking). GAPS `lsys-timerfd-gettime`.
        src("timerfd-gettime", "ext_linuxsys/timerfd_gettime.c").oracle().xfail(LIN),
        // signalfd realtime queue: only the first siginfo carries the right ssi_signo. GAPS `lsys-signalfd-rt`.
        src("signalfd-rt", "ext_linuxsys/signalfd_rt.c").oracle().xfail(LIN),
    ])
}

/// fs-flavoured Linux syscalls: inotify, memfd sealing, splice family, copy_file_range, statfs, sync.
fn fsx() -> Group {
    group("lsys-fs", vec![
        // inotify IN_MODIFY/IN_ATTRIB/IN_DELETE_SELF on a watched file — emulated correctly.
        src("inotify-modify", "ext_linuxsys/inotify_modify.c").oracle(),
        // inotify rename events (IN_MOVED_FROM/IN_MOVED_TO) are never generated by the JIT. GAPS `lsys-inotify-moves`.
        src("inotify-moves", "ext_linuxsys/inotify_moves.c").oracle().xfail(LIN),
        // memfd F_ADD_SEALS / F_SEAL_WRITE not enforced (writes after sealing still succeed). GAPS `lsys-memfd-seal`.
        src("memfd-seal", "ext_linuxsys/memfd_seal.c").oracle().xfail(LIN),
        // tee(2) unimplemented on the JIT (returns failure; no pipe-to-pipe duplication). GAPS `lsys-tee`.
        src("tee", "ext_linuxsys/tee.c").oracle().xfail(LIN),
        // vmsplice(2) unimplemented on the JIT. GAPS `lsys-vmsplice`.
        src("vmsplice", "ext_linuxsys/vmsplice.c").oracle().xfail(LIN),
        src("copy-file-range", "ext_linuxsys/copy_file_range.c").oracle(),
        src("fstatfs", "ext_linuxsys/fstatfs.c").oracle(),
        // syncfs(2) returns nonzero on the JIT (native returns 0). GAPS `lsys-syncfs`.
        src("syncfs", "ext_linuxsys/syncfs.c").oracle(),
    ])
}

/// process control: prctl variants, pidfd, gettid, unshare.
fn procx() -> Group {
    group("lsys-proc", vec![
        // PR_GET_NO_NEW_PRIVS returns -1 (the nnp bit isn't tracked). GAPS `lsys-prctl-nnp`.
        src("prctl-nnp", "ext_linuxsys/prctl_nnp.c").oracle().xfail(LIN),
        // PR_GET_DUMPABLE doesn't reflect PR_SET_DUMPABLE. GAPS `lsys-prctl-dumpable`.
        src("prctl-dumpable", "ext_linuxsys/prctl_dumpable.c").oracle().xfail(LIN),
        // PR_GET_PDEATHSIG fails / returns no signal. GAPS `lsys-prctl-pdeathsig`.
        src("prctl-pdeathsig", "ext_linuxsys/prctl_pdeathsig.c").oracle().xfail(LIN),
        src("gettid", "ext_linuxsys/gettid.c").oracle(),
        // pidfd_open(2) unsupported on the JIT (returns failure). GAPS `lsys-pidfd`.
        src("pidfd-open", "ext_linuxsys/pidfd_open.c").oracle(),
        // pidfd_send_signal: the aarch64 JIT doesn't deliver the signal (engine gap). On x86_64 the JIT
        // now delivers it correctly (killed=1) but the qemu-user oracle can't pidfd_send_signal (killed=0)
        // -> oracle artifact, not an engine gap (cf. clone3). GAPS `lsys-pidfd`.
        src("pidfd-signal", "ext_linuxsys/pidfd_signal.c").oracle().xfail(LIN),
        src("unshare-files", "ext_linuxsys/unshare_files.c").oracle(),
        // process_vm_readv: the aarch64 JIT now implements it (matches native). On x86_64 the JIT reads
        // correctly (read=32 ok=1) but the qemu-user oracle lacks process_vm_readv (read=-1) -> oracle
        // artifact, not an engine gap (cf. clone3). GAPS `lsys-process-vm`.
        src("process-vm", "ext_linuxsys/process_vm.c").oracle().xfail(&[Engine::LinuxX86_64]),
    ])
}

/// scheduler & cpu-topology syscalls.
fn schedx() -> Group {
    group("lsys-sched", vec![
        src("sched-yield", "ext_linuxsys/sched_yield.c").oracle(),
        src("sched-affinity", "ext_linuxsys/sched_affinity.c").oracle(),
        src("getcpu", "ext_linuxsys/getcpu.c").oracle(),
    ])
}

/// the long tail: getrandom flags, io_uring setup, membarrier, personality, clocks, fanotify, ioprio.
fn miscx() -> Group {
    group("lsys-misc", vec![
        src("getrandom-flags", "ext_linuxsys/getrandom_flags.c").oracle(),
        // io_uring_setup fails on the aarch64 JIT (x86_64 works). GAPS `lsys-io-uring`.
        src("io-uring", "ext_linuxsys/io_uring.c").oracle().xfail(&[Engine::LinuxAarch64]),
        // membarrier(2) MEMBARRIER_CMD_QUERY returns -1 (unimplemented). GAPS `lsys-membarrier`.
        src("membarrier", "ext_linuxsys/membarrier.c").oracle(),
        // personality(2) returns -1 (unimplemented). GAPS `lsys-personality`.
        src("personality", "ext_linuxsys/personality.c").oracle().xfail(LIN),
        src("clock-linux", "ext_linuxsys/clock_linux.c").oracle(),
        // fanotify_init on the aarch64 JIT fails with errno!=EPERM (ENOSYS-shaped); native gives EPERM
        // for an unprivileged caller. x86_64 matches native. GAPS `lsys-fanotify`.
        src("fanotify", "ext_linuxsys/fanotify.c").oracle().xfail(&[Engine::LinuxAarch64]),
        src("ioprio", "ext_linuxsys/ioprio.c").oracle(),
    ])
}
